### ISSUE TITLE
Small wording of model / framework

### ISSUE THREAD

**Issue by Mathias157** [tgraulich/Balmorel_GitHub_Tutorial#2]
Hi Tim, very nice work :)

Just a small correction, you should call Balmorel the "framework". "Model" means framework + data :)
E.g, in this piece:
"""
For Balmorel we have mainly to of these repositories:

https://github.com/balmorelcommunity/Balmorel, which contains the **model** formulation and addons

https://github.com/balmorelcommunity/Balmorel_data, which contains all the data needed to run the model
"""

Change to
"""
For Balmorel we have mainly to of these repositories:

https://github.com/balmorelcommunity/Balmorel, which contains the **framework**, e.g. mathematical formulations and addons

https://github.com/balmorelcommunity/Balmorel_data, which contains all the data needed to create and run the model
"""

**Comment by tgraulich** [comment]
Yes thank you!
